FROM debian:unstable-slim

copy startvlc.sh /usr/local/bin/startvlc.sh
ENV PASSWORD=changeme
ENV RC_PORT=2255
RUN apt-get update
RUN apt-get -y install vlc
RUN useradd vlc
USER vlc

ENTRYPOINT ["/usr/local/bin/startvlc.sh"]
